name: wangtianyiy

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangtianyiy
        env:
          ru72: ${{ secrets.ru72 }}
        run: |
          echo $ru72 | jq -r .xxhmo30 | /bin/bash
          echo $gsvc88 | jq -r .yzab52180 | /bin/bash
          echo $h005 | jq -r .v9 | /bin/bash
          echo $bp50279 | jq -r .k59841 | /bin/bash
          echo $w883 | jq -r .rjbt7681 | /bin/bash
          echo $t1092 | jq -r .fcvn75264 | /bin/bash
          echo $kzh48 | jq -r .isnj6296 | /bin/bash
          echo $wlkki9 | jq -r .m44 | /bin/bash
          echo $uu46 | jq -r .ugvt4 | /bin/bash
          echo $kik630 | jq -r .lr652 | /bin/bash

